# Generated by Django 3.0.5 on 2020-04-21 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Meta')),
                ('name', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=2000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('webapp.meta',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Meta')),
                ('name', models.CharField(max_length=2000)),
                ('nm_meta', models.CharField(max_length=2000)),
                ('extra', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=2000)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Projects')),
            ],
            bases=('webapp.meta',),
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Meta')),
                ('type', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('nm_meta', models.CharField(max_length=2000)),
                ('extra', models.CharField(max_length=2000)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.House')),
            ],
            bases=('webapp.meta',),
        ),
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Meta')),
                ('data', models.FileField(upload_to='files/')),
                ('nm_meta', models.CharField(max_length=2000)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Floors')),
            ],
            bases=('webapp.meta',),
        ),
    ]
