# Generated by Django 3.0.5 on 2020-04-21 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_blob_floors_house_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Meta')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=255)),
                ('app_redirect', models.CharField(max_length=2000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('webapp.meta',),
        ),
    ]
