# Generated by Django 3.0.5 on 2020-04-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='extra',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='projects',
            name='nm_meta',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='floors',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Projects'),
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
