# Generated by Django 3.0.5 on 2020-04-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200424_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='nm_meta',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='floors',
            name='extra',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='floors',
            name='nm_meta',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
